services:
  web:
    image: registry.gitlab.com/mirea8261545/security-lab-5-project/test:latest
    expose:
      - 5000:5000
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  redis:
    hostname: redis
    image: redis:7-alpine
    environment:
      - CONFFILE=/etc/redis.conf
      - REDIS_DATA_DIR=/data
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis.conf:/etc/redis.conf:ro
    restart: unless-stopped

  db:
    hostname: db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    ports:
      - 5432:5432
    restart: unless-stopped

