services:
  web:
    image: flask_app_pract_5/test:latest
    build:
      context: ..
      dockerfile: run/Test.Dockerfile
    hostname: web
    ports:
      - 3000:5000
    depends_on:
      - db
      - redis
    environment:
      - FLASK_ENV=testing
      - TESTING=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./data/test:/app/data

  redis:
    image: redis:7-alpine
    hostname: redis
    environment:
      - CONFFILE=/etc/redis.conf
      - REDIS_DATA_DIR=/data
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis.conf:/etc/redis.conf:ro
    command: ["redis-server", "/etc/redis.conf"]
    restart: unless-stopped

  db:
    image: postgres:13.1-alpine
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  db_data:
